language: node_js
dist: trusty
sudo: required
cache:
  directories:
    - node_modules
notifications:
  slack:
      on_success: change
      on_failure: always
node_js:
  - 'node'
  - '7'
  - '6'
before_install:
  - npm i -g npm@latest
  - npm install -g greenkeeper-lockfile
before_script:
  - greenkeeper-lockfile-update
  - npm prune
after_script:
  - greenkeeper-lockfile-upload
after_success:
  - npm run coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - npx -p node@8 npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
