language: node_js
cache:
  directories:
    - node_modules
notifications:
  slack:
      on_success: change
      on_failure: always
node_js:
  - '7'
  - '6'
  - '4'
before_script:
  - npm prune
after_success:
  - npm run coverage
  - cat coverage/lcov.info | node_modules/.bin/coveralls
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
